name: Deploy to Server

on:
  pull_request:
    types: [closed] # Trigger on PR merge
    branches:
      - main

jobs:
  # Job for dependency submission
  dependency-submission:
    runs-on: ubuntu-latest # Default runner provided by GitHub
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js and npm
        run: |
          sudo apt update -y
          sudo apt install nodejs npm -y

      # Automatically detect and report build-time dependencies
      - name: Submit Dependencies
        run: |
          echo "Submitting build-time dependencies for ecosystem..."
          npm install  || { echo "npm install failed"; exit 1; }

  # Job for deployment
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest # Use the default GitHub runner for deployment

    steps:
      # Checkout your repository
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      # Set up SSH key for deployment
      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      # Deploy to your server
      - name: Deploy to Server
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
          VITE_SUPABASE_URL: ${{ secrets.PROD_VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.PROD_VITE_SUPABASE_ANON_KEY }}
        run: |
          # Determine port based on branch
          if [ "$BRANCH_NAME" = "main" ]; then
            PORT=5173
          else
            echo "Unsupported branch: $BRANCH_NAME" && exit 1
          fi

          # Set environment variables based on branch
          VITE_SUPABASE_URL=$VITE_SUPABASE_URL
          VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY

          # Set up SSH key
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

          # SSH into the server and deploy
          ssh -t -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_HOST << EOF
            # Ensure correct permissions for the repository directory
            sudo chown -R $SERVER_USER:$SERVER_USER /home/$SERVER_USER/websites/laser-magique
            sudo chmod -R 755 /home/$SERVER_USER/websites/laser-magique
            sudo find /home/$SERVER_USER/websites/laser-magique -type f -exec chmod +rw {} \;

            # Remove existing laser-magique directory
            if [ -d "/home/$SERVER_USER/websites/laser-magique" ]; then
              echo "Removing existing laser-magique directory..."
              echo "$SUDO_PASSWORD" | sudo -S rm -rf /home/$SERVER_USER/websites/laser-magique || { echo "Failed to remove directory"; exit 1; }
            fi

            # Clone the repository using SSH
            echo "Cloning the repository branch: $BRANCH_NAME..."
            git clone --branch $BRANCH_NAME git@github.com:Thimote147/laser-magique.git /home/$SERVER_USER/websites/laser-magique || { echo "Git clone failed"; exit 1; }

            # Set permissions for the repository
            sudo chown -R $SERVER_USER:$SERVER_USER /home/$SERVER_USER/websites/laser-magique
            sudo chmod -R 755 /home/$SERVER_USER/websites/laser-magique

            # Create the .env file for environment variables
            echo "VITE_SUPABASE_URL=$VITE_SUPABASE_URL" > /home/$SERVER_USER/websites/laser-magique/.env
            echo "VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY" >> /home/$SERVER_USER/websites/laser-magique/.env

            # Navigate to the project directory and build
            cd /home/$SERVER_USER/websites/laser-magique
            npm install
            npm run build

            # Remove existing Docker container if exists
            if docker ps -a --format '{{.Names}}' | grep -q "laser-magique"; then
              docker stop laser-magique || true
              docker rm -f laser-magique || true
            else
              echo "Container laser-magique does not exist."
            fi

            # Clean up old Docker images
            docker image prune -f

            # Build and run the Docker container
            cd /home/$SERVER_USER/websites/laser-magique
            docker build -t laser-magique . || { echo "Docker build failed"; exit 1; }

            # For prod, use the default dist folder (dist)
            docker cp /home/$SERVER_USER/websites/laser-magique/dist/. laser-magique:/usr/share/nginx/html

            echo "Running Docker container #laser-magique at port $PORT..."
            docker run -d --name laser-magique -p "$PORT:5173" --env-file .env laser-magique || { echo "Docker run failed"; exit 1; }
          EOF
