name: Block Certain Branch Merge Into Main

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if pull request is trying to merge from a feature branch to main
        run: |
          TARGET_BRANCH="${GITHUB_BASE_REF}"
          SOURCE_BRANCH="${GITHUB_HEAD_REF}"

          # Check if the PR is targeting 'main' and not coming from 'dev'
          if [[ "$TARGET_BRANCH" == "main" && ("$SOURCE_BRANCH" != "dev" && "$SOURCE_BRANCH" != "dependabot" && "$SOURCE_BRANCH" != "fix") ]]; then
            echo "Error: Merging from a feature branch other than 'dev' (and 'dependabot') into 'main' is not allowed.";
            exit 1;
          fi
